
set_property PACKAGE_PIN W5 [get_ports CLOCK]							
	set_property IOSTANDARD LVCMOS33 [get_ports CLOCK]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports CLOCK]
 

set_property PACKAGE_PIN V17 [get_ports {SW}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {SW}]


set_property PACKAGE_PIN W7 [get_ports {LED_out_o[6]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[6]}]
        set_property PACKAGE_PIN W6 [get_ports {LED_out_o[5]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[5]}]
        set_property PACKAGE_PIN U8 [get_ports {LED_out_o[4]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[4]}]
        set_property PACKAGE_PIN V8 [get_ports {LED_out_o[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[3]}]
        set_property PACKAGE_PIN U5 [get_ports {LED_out_o[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[2]}]
        set_property PACKAGE_PIN V5 [get_ports {LED_out_o[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[1]}]
        set_property PACKAGE_PIN U7 [get_ports {LED_out_o[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {LED_out_o[0]}]
        set_property PACKAGE_PIN U2 [get_ports {Anode_Activate_o[0]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate_o[0]}]
        set_property PACKAGE_PIN U4 [get_ports {Anode_Activate_o[1]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate_o[1]}]
        set_property PACKAGE_PIN V4 [get_ports {Anode_Activate_o[2]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate_o[2]}]
        set_property PACKAGE_PIN W4 [get_ports {Anode_Activate_o[3]}]                    
            set_property IOSTANDARD LVCMOS33 [get_ports {Anode_Activate_o[3]}]



set_property PACKAGE_PIN T18 [get_ports {KEY[2]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {KEY[2]}]
set_property PACKAGE_PIN W19 [get_ports {KEY[3]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {KEY[3]}]
set_property PACKAGE_PIN T17 [get_ports {KEY[0]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {KEY[0]}]
set_property PACKAGE_PIN U17 [get_ports {KEY[1]}]						
	set_property IOSTANDARD LVCMOS33 [get_ports {KEY[1]}]
 


set_property PACKAGE_PIN G19 [get_ports {VGA_R[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[0]}]
set_property PACKAGE_PIN H19 [get_ports {VGA_R[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[1]}]
set_property PACKAGE_PIN J19 [get_ports {VGA_R[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[2]}]
set_property PACKAGE_PIN N19 [get_ports {VGA_R[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_R[3]}]
set_property PACKAGE_PIN N18 [get_ports {VGA_B[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[0]}]
set_property PACKAGE_PIN L18 [get_ports {VGA_B[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[1]}]
set_property PACKAGE_PIN K18 [get_ports {VGA_B[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[2]}]
set_property PACKAGE_PIN J18 [get_ports {VGA_B[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_B[3]}]
set_property PACKAGE_PIN J17 [get_ports {VGA_G[0]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[0]}]
set_property PACKAGE_PIN H17 [get_ports {VGA_G[1]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[1]}]
set_property PACKAGE_PIN G17 [get_ports {VGA_G[2]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[2]}]
set_property PACKAGE_PIN D17 [get_ports {VGA_G[3]}]				
	set_property IOSTANDARD LVCMOS33 [get_ports {VGA_G[3]}]
set_property PACKAGE_PIN P19 [get_ports VGA_HS]						
	set_property IOSTANDARD LVCMOS33 [get_ports VGA_HS]
set_property PACKAGE_PIN R19 [get_ports VGA_VS]						
	set_property IOSTANDARD LVCMOS33 [get_ports VGA_VS]


